name: Java CI

on:
  - push
  - pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - run: make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env: 
          CC_TEST_REPORTER_ID: ea16dec98c15f23a50cbae9be539cd3d380b90f4664f56f9b1baabbeecbf214c
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make reported
          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
